// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoI637UmjQg_DABUN6xXeOTZYuI4ZB0Rg',
    appId: '1:763165796727:web:b6690433a52052d1cf9972',
    messagingSenderId: '763165796727',
    projectId: 'newgensports-85bb4',
    authDomain: 'newgensports-85bb4.firebaseapp.com',
    storageBucket: 'newgensports-85bb4.firebasestorage.app',
    measurementId: 'G-GDX261889H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRz-XEMioQJCy21W61nPcBQ7OUH2qYu4',
    appId: '1:763165796727:android:5f4a83f466a4f744cf9972',
    messagingSenderId: '763165796727',
    projectId: 'newgensports-85bb4',
    storageBucket: 'newgensports-85bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Qgz6CjA3d_-QdhJMKSwCEI3HSCcb2e0',
    appId: '1:763165796727:ios:4bf1080ccca8f8c2cf9972',
    messagingSenderId: '763165796727',
    projectId: 'newgensports-85bb4',
    storageBucket: 'newgensports-85bb4.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Qgz6CjA3d_-QdhJMKSwCEI3HSCcb2e0',
    appId: '1:763165796727:ios:4bf1080ccca8f8c2cf9972',
    messagingSenderId: '763165796727',
    projectId: 'newgensports-85bb4',
    storageBucket: 'newgensports-85bb4.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoI637UmjQg_DABUN6xXeOTZYuI4ZB0Rg',
    appId: '1:763165796727:web:e7b40956ee4a4c5ccf9972',
    messagingSenderId: '763165796727',
    projectId: 'newgensports-85bb4',
    authDomain: 'newgensports-85bb4.firebaseapp.com',
    storageBucket: 'newgensports-85bb4.firebasestorage.app',
    measurementId: 'G-QZF9DY01LD',
  );
}
